import Link from "next/link";

// A working draft, same caveat as the Privacy Policy: not a
// substitute for a lawyer's review. Written to cover what actually
// matters for a predictions site specifically -- the disclaimer that
// win probabilities are model output, not guarantees or gambling
// advice, since that's the real liability surface here, not
// boilerplate.
export const metadata = {
  title: "Terms of Service — Matrix Sports Analytics",
};

export default function TermsPage() {
  return (
    <>
      <header className="site-header">
        <h1 className="glow">TERMS OF SERVICE</h1>
        <p className="subtitle">{"// last updated September 2026"}</p>
      </header>

      <main className="about-main">
        <section className="about-block">
          <div className="section-label">
            <span className="dot" /> ACCEPTANCE OF TERMS
          </div>
          <p>
            By using matrixsports.net (&quot;the site&quot;), you agree to
            these terms. If you don&apos;t agree, don&apos;t use the site. We
            may update these terms as the site changes — see &quot;Changes to
            These Terms&quot; below.
          </p>
        </section>

        <section className="about-block">
          <div className="section-label">
            <span className="dot" /> WHAT THIS SITE IS — AND ISN&apos;T
          </div>
          <p>
            Matrix Sports Analytics publishes simulated NFL win probabilities
            and related statistics, generated by running each matchup through
            a Monte Carlo model grounded in the published market line. It is
            an analytics and entertainment product.
          </p>
          <p>
            <strong>
              This site does not accept wagers, is not a sportsbook, and does
              not facilitate gambling in any way.
            </strong>{" "}
            Nothing on this site is gambling, financial, or betting advice.
            Win probabilities are model estimates, not predictions of
            certainty — a team with a 90% simulated win probability can and
            does lose. Any decision you make based on content here,
            including any bet you place with a third party, is entirely your
            own responsibility.
          </p>
        </section>

        <section className="about-block">
          <div className="section-label">
            <span className="dot" /> WHO CAN USE THIS SITE
          </div>
          <p>
            You must be at least 13 years old to create an account. Some
            content on this site references sports betting lines published
            by third-party sportsbooks; if you choose to click through to a
            sportsbook via any link on this site, you must independently meet
            that operator&apos;s own age and location requirements (typically
            21+ and only in jurisdictions where sports betting is legal). We
            don&apos;t verify this for you.
          </p>
        </section>

        <section className="about-block">
          <div className="section-label">
            <span className="dot" /> YOUR ACCOUNT
          </div>
          <p>
            You&apos;re responsible for keeping your login credentials secure
            and for anything that happens under your account. Give us
            accurate information when you sign up. We can suspend or
            terminate accounts that violate these terms, abuse the service,
            or attempt to circumvent access restrictions (like the free/paid
            gating on the full weekly slate).
          </p>
        </section>

        <section className="about-block">
          <div className="section-label">
            <span className="dot" /> ACCEPTABLE USE
          </div>
          <p>
            Don&apos;t scrape, bulk-download, or systematically extract
            predictions or data from this site for redistribution or
            resale. Don&apos;t attempt to disrupt, reverse-engineer, or
            gain unauthorized access to the site or its underlying model.
            Don&apos;t use the site for anything illegal.
          </p>
        </section>

        <section className="about-block">
          <div className="section-label">
            <span className="dot" /> FREE ACCESS, SUBSCRIPTIONS &amp; PRICING
          </div>
          <p>
            The site is currently free to use during its beta period,
            including for early subscribers who create a free account now.
            We intend to introduce paid subscription tiers in the future;
            accounts created during beta are intended to receive
            preferential pricing when that happens, but this isn&apos;t a
            binding guarantee of any specific price or feature set, and we
            may change our pricing and feature plans as the product
            develops.
          </p>
        </section>

        <section className="about-block">
          <div className="section-label">
            <span className="dot" /> ADVERTISING &amp; THIRD-PARTY LINKS
          </div>
          <p>
            This site may display third-party advertising and affiliate
            links. We aren&apos;t responsible for the content, accuracy, or
            practices of any third-party site you reach through an ad or
            link here — see our{" "}
            <Link href="/privacy">Privacy Policy</Link> for more on how those
            work.
          </p>
        </section>

        <section className="about-block">
          <div className="section-label">
            <span className="dot" /> INTELLECTUAL PROPERTY
          </div>
          <p>
            The site&apos;s design, model output, and written content belong
            to Matrix Sports Analytics. You&apos;re welcome to view and share
            individual pages (a link to a game&apos;s prediction, for
            example), but you may not republish, resell, or systematically
            reproduce our predictions or data as your own product or feed.
          </p>
        </section>

        <section className="about-block">
          <div className="section-label">
            <span className="dot" /> NO WARRANTY
          </div>
          <p>
            The site and its predictions are provided &quot;as is,&quot;
            without warranty of any kind. We don&apos;t guarantee the
            accuracy, completeness, or reliability of any prediction, stat,
            or piece of content — models are wrong sometimes, that&apos;s the
            nature of simulating an uncertain event, and real-world sports
            data feeds (scores, schedules) can occasionally be delayed or
            incorrect through no fault of ours.
          </p>
        </section>

        <section className="about-block">
          <div className="section-label">
            <span className="dot" /> LIMITATION OF LIABILITY
          </div>
          <p>
            To the fullest extent permitted by law, Matrix Sports Analytics
            isn&apos;t liable for any loss or damage arising from your use of
            the site, your reliance on any prediction or content here, or
            any action you take (including any wager placed with a
            third-party sportsbook) based on it.
          </p>
        </section>

        <section className="about-block">
          <div className="section-label">
            <span className="dot" /> CHANGES TO THESE TERMS
          </div>
          <p>
            We may update these terms as the site changes. Meaningful changes
            will be reflected by updating the date at the top of this page.
          </p>
        </section>

        <section className="about-block">
          <div className="section-label">
            <span className="dot" /> CONTACT
          </div>
          <p>
            Questions about these terms: reach us at{" "}
            <a href="mailto:privacy@matrixsports.net">privacy@matrixsports.net</a>
            . See also our <Link href="/privacy">Privacy Policy</Link>.
          </p>
        </section>
      </main>

      <footer className="site-footer">
        <p>
          This page is a working draft describing our actual practices, not a
          substitute for professional legal advice.
        </p>
      </footer>
    </>
  );
}
