-- stories -- AI-drafted short narrative write-ups about a completed
-- game (e.g. "the model gave the Jets a 42% chance and they covered
-- by 13"), generated by a scheduled Netlify function
-- (netlify/functions/weekly-stories.mts) strictly from real final
-- scores/records already in latest_predictions -- never from an LLM's
-- own free-recall "sports trivia," which is exactly what produces a
-- wrong stat (see the ltorres/Claude conversation this shipped from:
-- a radio-heard "Jets' first win since 2009" turned out to be false --
-- real number was 2023). source_facts keeps the exact JSON handed to
-- the model so a published story's claims can always be checked back
-- against what actually grounded it.
--
-- Same access model as admin_users/predictions: no client-facing RLS
-- policies. Every read (public site) and write (the generator
-- function, and the admin approve/reject actions) goes through the
-- app's own server-side Postgres pool, never through Supabase's
-- RLS-gated client REST API -- RLS is enabled here only as a
-- belt-and-suspenders default-deny.
--
-- Run once against the database DATABASE_URL points at:
--   psql "$DATABASE_URL" -f sql/010_stories_schema.sql

CREATE TABLE IF NOT EXISTS stories (
    id                 UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    season             INTEGER NOT NULL,
    week               INTEGER NOT NULL,
    universal_game_id  TEXT,
    headline           TEXT NOT NULL,
    body               TEXT NOT NULL,
    source_facts       JSONB NOT NULL,
    model_used         TEXT,
    status             TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'published', 'rejected')),
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    published_at       TIMESTAMPTZ,
    UNIQUE (universal_game_id)
);

CREATE INDEX IF NOT EXISTS idx_stories_status_created ON stories (status, created_at DESC);

ALTER TABLE stories ENABLE ROW LEVEL SECURITY;
